@startuml Pickup
title Marketplace Pickup
Shipt_com -[#blue]-> open
Shipt_com : shipt.com allows members to submit orders
open : member has created an order

open -[#green]-> claimed
claimed : shopper has claimed the delivery 

claimed -[#green]-> shopping
shopping : shopper is at the partner's store

shopping -[#green]-> processed
processed : order has been checked out and credit card charged

processed -[#green]-> ready_for_pickup
ready_for_pickup : order is ready for the customer to pick up at the store

ready_for_pickup -[#green]-> delivered
delivered : order has been delivered to the customer

processed -[#red]-> returned
ready_for_pickup -[#red]-> returned
returned : order is returned

open -[#red]-> cancelled
claimed -[#red]-> cancelled
shopping -[#red]-> cancelled
processed -[#red]-> cancelled
cancelled : order is cancelled

cancelled -[#red]-> [*]
returned -[#red]-> [*]
delivered -[#green]-> [*]
@enduml