@startuml Platform
title Platform
Platform_Broker -[#blue]-> open
Platform_Broker : API entry point for Platform Orders
open : member has created an order

open -[#green]-> claimed
claimed : shopper has claimed the delivery 

claimed -[#green]-> shopping
shopping : shopper is at the partner's store

shopping -[#green]-> processed
processed : order has been checked out and credit card charged

processed -[#green]-> delivered
delivered : shopper has dropped off the order to the customer

processed -[#red]-> returned
delivered -[#red]-> returned
returned : order is returned

open -[#red]-> cancelled
claimed -[#red]-> cancelled
shopping --[#red]> cancelled
processed -[#red]-> cancelled
cancelled : order is cancelled

cancelled -[#red]-> [*]
returned -[#red]-> [*]
delivered -[#green]-> [*]
@enduml